@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
scale 1.3

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class UniqueBookingList
Class Person
Class Booking

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .right.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
AddressBook *--> "1" UniqueBookingList
AddressBook *-[hidden]-> Booking

' Collections to entities
UniqueBookingList -down-> "~* all" Booking

UniquePersonList -[hidden]down-> "~* all" Person
UniquePersonList -down-> "~* all" Person
UniquePersonList -[hidden]down-> Booking

Booking "*"-right--> "1" Person
note right of Booking
  A Booking object is created based
  on an existing Person object.
  It stores a copy of the Person's Name,
  but does not keep a direct reference to the Person.
end note

ModelManager -down-> "~* modified" Person
ModelManager --> "~* modified" Booking

Person -[hidden]up-> I
UniquePersonList -[hidden]right-> I
@enduml
